version: "3.1"

services:
  node_app:
    platform: linux/amd64
    build:
      context: ./source
    #image: amd64/node_app:14
    ports: 
      - "5001:5001"
    
   
    
    networks:
      - my-network
    


  mongodb:
    
    platform: linux/amd64
    
    build:
      context: ./mongodb
    image: amd64/mongo:4.4
    ports:
      - "27017:27017"
  
    networks:
      - my-network
    


networks:
  my-network:
    driver: bridge

